"""Core data models for HypoGen.

These Pydantic models flow through the entire pipeline:
  CausalClaim  →  KnowledgeEdge  →  GapNode  →  Hypothesis

All are serialisable to JSON for persistence and API responses.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field


class CausalClaim(BaseModel):
    """A causal relationship extracted from one paper.

    Represents a single LLM extraction result from one paragraph/section of
    one paper. Multiple claims for the same (cause, effect) pair across papers
    are later merged into a ``KnowledgeEdge``.
    """

    cause: str = Field(description="The causing variable or factor (lowercase, concise).")
    effect: str = Field(description="The caused variable or factor (lowercase, concise).")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="How confident this is a causal (not correlational) relationship.",
    )
    mechanism: str = Field(
        description="Brief mechanistic explanation of how cause produces the effect."
    )
    source_paper: str = Field(description="Filename or title of the source paper.")
    evidence: str = Field(description="Exact sentence(s) from the paper supporting this claim.")


class KnowledgeEdge(BaseModel):
    """Aggregated edge in the knowledge graph.

    Created by merging all ``CausalClaim`` instances that share the same
    (cause, effect) pair. Represents community-level knowledge about a
    causal relationship.
    """

    cause: str
    effect: str
    avg_confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Mean confidence across all supporting papers.",
    )
    paper_count: int = Field(
        ge=1,
        description="Number of distinct papers that mention this edge.",
    )
    mechanisms: list[str] = Field(
        default_factory=list,
        description="All mechanistic explanations collected from supporting papers.",
    )
    evidence_sentences: list[str] = Field(
        default_factory=list,
        description="All evidence sentences collected from supporting papers.",
    )


class GapNode(BaseModel):
    """A structural gap in the causal knowledge graph.

    Gaps represent places where the graph is incomplete — a variable that
    should have causal ancestors or descendants but doesn't, broken chains,
    or low-confidence links in otherwise solid knowledge paths.
    """

    variable: str = Field(description="The graph node at the centre of this gap.")
    gap_type: Literal[
        "MISSING_CAUSE",
        "MISSING_EFFECT",
        "ISOLATED_NODE",
        "LOW_CONFIDENCE_CHAIN",
        "BROKEN_CHAIN",
    ] = Field(description="Structural classification of the gap.")
    gap_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Importance score: 0=minor gap, 1=major gap worth investigating.",
    )
    neighboring_nodes: list[str] = Field(
        default_factory=list,
        description="Direct graph neighbours (causes and effects) of this node.",
    )
    existing_edges: list[str] = Field(
        default_factory=list,
        description="Human-readable descriptions of edges touching this node.",
    )
    gap_explanation: str = Field(
        description="Plain-English explanation of why this is a gap and why it matters."
    )


class Hypothesis(BaseModel):
    """A novel, testable scientific hypothesis grounded in the knowledge graph.

    Generated by the LLM using the gap as context. Every field is
    grounded in the graph — no pure hallucination.
    """

    id: str = Field(description="Unique identifier, e.g. 'H001'.")
    gap_addressed: GapNode = Field(description="The knowledge gap this hypothesis addresses.")
    hypothesis_text: str = Field(
        description="Full hypothesis statement, e.g. 'We hypothesize that X causes Y via Z'."
    )
    predicted_cause: str = Field(description="The proposed causal variable.")
    predicted_effect: str = Field(description="The proposed effect variable.")
    predicted_mechanism: str = Field(
        description="Specific biological/physical/chemical mechanism proposed."
    )
    testability_score: float = Field(
        ge=0.0,
        le=1.0,
        description="How feasible it is to test this with realistic experiments (0=untestable).",
    )
    novelty_score: float = Field(
        ge=0.0,
        le=1.0,
        description="How novel this is vs. existing literature in the graph (0=already known).",
    )
    suggested_experiment: str = Field(
        description="Concrete experimental design that would test this hypothesis."
    )
    supporting_context: str = Field(
        description="Which existing graph edges and mechanisms support or motivate this hypothesis."
    )


class KnowledgeGraph(BaseModel):
    """Complete snapshot of the causal knowledge graph and derived outputs.

    This is the main serialisable state object — saved to JSON and loaded
    for gap analysis, hypothesis generation, and visualisation.
    """

    nodes: list[str] = Field(default_factory=list, description="All variable names in the graph.")
    edges: list[KnowledgeEdge] = Field(
        default_factory=list, description="All aggregated causal edges."
    )
    claims: list[CausalClaim] = Field(
        default_factory=list, description="All raw claims extracted from papers."
    )
    papers_analyzed: int = Field(default=0, description="Number of papers processed.")
    gaps: list[GapNode] = Field(
        default_factory=list, description="Detected structural gaps, sorted by gap_score desc."
    )
    hypotheses: list[Hypothesis] = Field(
        default_factory=list, description="Generated hypotheses, sorted by combined score desc."
    )
    created_at: str = Field(description="ISO 8601 timestamp of when this graph was created.")
    model_used: str = Field(
        default="unknown", description="LiteLLM model string used for extraction."
    )
